# Generated by Django 4.2.2 on 2023-06-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0004_exercice_difficulte"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercice",
            old_name="partie_de_cours",
            new_name="partie_cours",
        ),
    ]
