# Generated by Django 4.2.2 on 2023-06-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0005_rename_partie_de_cours_exercice_partie_cours"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="cours",
            field=models.CharField(default="Cours1", max_length=512),
        ),
    ]
