# Generated by Django 4.2.2 on 2023-06-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0006_correction_cours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correction",
            name="nombre_de_methode",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="correction",
            name="theoreme",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
