# Generated by Django 4.2.2 on 2023-06-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="correction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ex_id", models.IntegerField()),
                ("nombre_de_methode", models.BooleanField()),
                ("commentaires", models.SmallIntegerField()),
                ("theoreme", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="exercice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cours", models.CharField(max_length=512)),
                ("partie_de_cours", models.CharField(max_length=512)),
                ("longueur", models.PositiveSmallIntegerField()),
                ("but", models.CharField(max_length=512)),
                ("ex_id", models.IntegerField()),
            ],
        ),
    ]
