# Generated by Django 4.2.2 on 2023-06-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correction",
            name="commentaires",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "minimum"), (1, "moyen"), (2, "trés explicatif")]
            ),
        ),
        migrations.AlterField(
            model_name="exercice",
            name="longueur",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "court"), (1, "long"), (2, "probleme")]
            ),
        ),
    ]
