# Generated by Django 4.2.2 on 2023-06-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0002_alter_correction_commentaires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="text",
            field=models.CharField(default="default_value_here", max_length=1024),
        ),
        migrations.AddField(
            model_name="exercice",
            name="text",
            field=models.CharField(default="default_value_here", max_length=1024),
        ),
    ]
