# Generated by Django 4.2.2 on 2023-06-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0003_correction_text_exercice_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercice",
            name="difficulte",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "facile"), (1, "moyen"), (2, "deficile")], default=0
            ),
        ),
    ]
