# Generated by Django 4.2.2 on 2023-06-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0007_alter_correction_nombre_de_methode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correction",
            name="nombre_de_methode",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="correction",
            name="theoreme",
            field=models.BooleanField(),
        ),
    ]
