# Generated by Django 4.2.2 on 2023-06-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0008_alter_correction_nombre_de_methode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercice",
            name="niveau",
            field=models.CharField(default="bac", max_length=512),
        ),
    ]
