# Generated by Django 4.2.2 on 2023-06-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0009_exercice_niveau"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correction",
            name="cours",
        ),
        migrations.RemoveField(
            model_name="exercice",
            name="ex_id",
        ),
    ]
