# Generated by Django 4.2.2 on 2023-06-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0010_remove_correction_cours_remove_exercice_ex_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="exercice",
            new_name="Exercise",
        ),
    ]
