# Generated by Django 4.2.2 on 2023-06-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0011_rename_exercice_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="CoursePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name="correction",
            name="text",
            field=models.TextField(default="default_value_here"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="text",
            field=models.TextField(default="default_value_here"),
        ),
    ]
