# Generated by Django 4.2.2 on 2023-06-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0012_course_coursepart_alter_correction_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepart",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profikapp.course",
            ),
        ),
    ]
