# Generated by Django 4.2.2 on 2023-06-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0013_coursepart_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepart",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profikapp.course",
            ),
        ),
    ]
