# Generated by Django 4.2.2 on 2023-06-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0014_alter_coursepart_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="cours",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profikapp.course"
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="partie_cours",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profikapp.coursepart"
            ),
        ),
    ]
