# Generated by Django 4.2.2 on 2023-06-15 12:21

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0015_alter_exercise_cours_alter_exercise_partie_cours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="partie_cours",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="cours",
                chained_model_field="course",
                on_delete=django.db.models.deletion.CASCADE,
                to="profikapp.coursepart",
            ),
        ),
    ]
