# Generated by Django 4.2.2 on 2023-06-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0016_alter_exercise_partie_cours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correction",
            name="commentaires",
        ),
        migrations.RemoveField(
            model_name="correction",
            name="ex_id",
        ),
        migrations.RemoveField(
            model_name="correction",
            name="nombre_de_methode",
        ),
        migrations.RemoveField(
            model_name="correction",
            name="theoreme",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="cours",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="partie_cours",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="text",
        ),
        migrations.AddField(
            model_name="correction",
            name="question_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exercise",
            name="course_part_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profikapp.coursepart",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.CharField(max_length=12)),
                ("text", models.TextField()),
                (
                    "exercise_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profikapp.exercise",
                    ),
                ),
            ],
        ),
    ]
