# Generated by Django 4.2.2 on 2023-06-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0017_remove_correction_commentaires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="commentaires",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "minimum"), (1, "moyen"), (2, "trés explicatif")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="correction",
            name="nombre_de_methode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="correction",
            name="theoreme",
            field=models.BooleanField(default=False),
        ),
    ]
