# Generated by Django 4.2.2 on 2023-06-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "profikapp",
            "0018_correction_commentaires_correction_nombre_de_methode_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="correction",
            old_name="commentaires",
            new_name="comments",
        ),
        migrations.RenameField(
            model_name="correction",
            old_name="nombre_de_methode",
            new_name="has_methods",
        ),
        migrations.RenameField(
            model_name="correction",
            old_name="theoreme",
            new_name="has_theorem",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="title",
            new_name="course_title",
        ),
        migrations.RenameField(
            model_name="coursepart",
            old_name="title",
            new_name="part_title",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="course_part_id",
            new_name="course_part",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="but",
            new_name="goal",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="longueur",
            new_name="length",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="niveau",
            new_name="level",
        ),
        migrations.RemoveField(
            model_name="correction",
            name="question_id",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="difficulte",
        ),
        migrations.RemoveField(
            model_name="question",
            name="exercise_id",
        ),
        migrations.AddField(
            model_name="correction",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profikapp.question",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="difficulty",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "facile"), (1, "moyen"), (2, "difficile")], default=0
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="profikapp.exercise",
            ),
        ),
    ]
