# Generated by Django 4.2.2 on 2023-06-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0019_rename_commentaires_correction_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="heading",
            field=models.TextField(default=""),
        ),
    ]
