# Generated by Django 4.2.2 on 2023-06-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profikapp", "0020_exercise_heading"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="heading",
            new_name="head",
        ),
    ]
