# Generated by Django 4.2.2 on 2023-07-03 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profikapp", "0022_rename_goal_exercise_reasoning"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="coursepart",
            old_name="part_title",
            new_name="title",
        ),
    ]
