# Generated by Django 4.2.2 on 2023-07-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profikapp", "0023_rename_course_title_course_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="level",
            field=models.CharField(
                choices=[
                    ("bac tech", "Bac technique"),
                    ("bac SC", "Bac science"),
                    ("bac math", "Bac math"),
                ],
                default="bac",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="reasoning",
            field=models.CharField(
                choices=[
                    (0, "normal"),
                    (1, "aléatoire"),
                    (2, "récurrence"),
                    (3, "absurd"),
                ],
                max_length=512,
            ),
        ),
    ]
