# Generated by Django 4.2.2 on 2023-07-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profikapp", "0024_alter_exercise_level_alter_exercise_reasoning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="reasoning",
            field=models.PositiveBigIntegerField(
                choices=[
                    (0, "normal"),
                    (1, "aléatoire"),
                    (2, "récurrence"),
                    (3, "absurd"),
                ],
                max_length=512,
            ),
        ),
    ]
