# Generated by Django 4.2.2 on 2023-07-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profikapp", "0026_alter_exercise_reasoning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profikapp.exercise",
            ),
        ),
    ]
