# Generated by Django 4.2.2 on 2023-07-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profikapp", "0028_alter_exercise_reasoning"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="course",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                to="profikapp.course",
            ),
        ),
    ]
