# Generated by Django 4.2.2 on 2023-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profikapp", "0029_exercise_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="resume",
            field=models.CharField(
                default="<p>$x=\x0crac{1}{y}$</p>", max_length=10000
            ),
        ),
    ]
