# Generated by Django 4.2.2 on 2023-08-08 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profikapp", "0032_remove_correction_has_methods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="reasoning",
        ),
    ]
